---
project_name: stackql

release:
  github:
    owner: stackql
    name: stackql

before:
  hooks:
    - go mod tidy
    - go mod download
    - go mod verify

builds:
  - id: stackql-linux
    binary: stackql
    main: ./stackql/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - BUILDPLATFORM = {{ .Env.BUILDPLATFORM }}
      - >-
        {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
      - >-
        {{- if eq .Arch "amd64"}}CXX=x86_64-linux-gnu-g++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=aarch64-linux-gnu-gcc{{- end }}
    flags:
      - -trimpath
    ldflags: >-
      -s -w
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildPlatform={{ .Env.BUILDPLATFORM }}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildMajorVersion={{ .Major }}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildMinorVersion={{ .Env.BUILDMINORVERSION }}}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildPatchVersion={{ .Env.BUILDPATCHVERSION }}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildCommitSHA={{ .Env.BUILDCOMMITSHA }}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildShortCommitSHA={{ .Env.BUILDSHORTCOMMITSHA }}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildDate={{ .Env.BUILDDATE }}
      -X stackql/internal/stackql/planbuilder.PlanCacheEnabled={{ .Env.PLANCACHEENABLED }}

archives:
  - format: tar.gz
    name_template: "stackql_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

checksum:
  name_template: "stackql_checksums.txt"

nfpms:
  - id: stackql-nfpms
    file_name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://stackql.io/
    maintainer: "StackQL Team <stackql-team@users.noreply.github.com>" # optional
    description: StackQL core project that enables users to interact with cloud resources using SQL.
    license: MIT
    section: golang
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    umask: 0o002
    overrides:
      deb:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/stackql/LICENSE
          - src: README.md
            dst: /usr/share/doc/stackql/README.md
        recommends:
          - golang-go
      rpm:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/stackql/LICENSE
            type: license
          - src: README.md
            dst: /usr/share/doc/stackql/README.md
            type: readme
        recommends:
          - /usr/bin/go
      apk:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/stackql/LICENSE
          - src: README.md
            dst: /usr/share/doc/stackql/README.md
      archlinux:
        contents:
          - src: LICENSE
            dst: /usr/share/doc/stackql/LICENSE
          - src: README.md
            dst: /usr/share/doc/stackql/README.md
    rpm:
      group: Development/Tools
