---
project_name: stackql

# release:
#   github:
#     owner: Iqbalabdi
#     name: stackql

before:
  hooks:
    - go mod tidy
    - go mod download
    - go mod verify

builds:
  - id: stackql-linux
    binary: stackql
    main: ./stackql/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
      - >-
        {{- if eq .Arch "amd64"}}CXX=x86_64-linux-gnu-g++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=aarch64-linux-gnu-gcc{{- end }}
    flags:
      - -trimpath
    ldflags: >-
      -s -w
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildMajorVersion={{.Major}}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildMinorVersion={{.Minor}}}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildPatchVersion={{.Patch}}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildCommitSHA={{.FullCommit}}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildShortCommitSHA={{.ShortCommit}}
      -X github.com/stackql/stackql/internal/stackql/cmd.BuildDate={{.Date}}
    # -X stackql/internal/stackql/planbuilder.PlanCacheEnabled={{.Env.PLANCACHEENABLED}}
    # -X github.com/stackql/stackql/internal/stackql/cmd.BuildPlatform={{.Env.BUILDPLATFORM}}

archives:
  - format: tar.gz
    name_template: "stackql_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

checksum:
  name_template: "stackql_checksums.txt"

nfpms:
  - id: stackql-nfpms
    file_name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: https://stackql.io/
    maintainer: "StackQL Team <stackql-team@users.noreply.github.com>" # optional
    description: StackQL core project that enables users to interact with cloud resources using SQL.
    license: MIT
    section: golang
    formats:
      - deb
      - rpm
      - apk
      - archlinux

dockers:
- image_templates: ["ghcr.io/stackql/example:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stackql/example
  - --label=org.opencontainers.image.source=https://github.com/stackql/example
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .Date }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT