name: build

on:
  push:
    branches:
      - 'dev'
    tags:
      - v*

# env:
#   GITHUB_TOKEN: ${{ secrets.ACTIONS_PRIVATE_PACKAGE_SECRET }}

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Install cross-compiler for linux/arm64
        run: sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Generate Build Flags and Build
        env:
          BUILDCOMMITSHA: ${{github.sha}}
          BUILDBRANCH: ${{github.ref}}
          BUILDPATCHVERSION: ${{github.run_number}}
          BUILDPLATFORM: ${{runner.os}}
          CGO_LDFLAGS: '-static'
        run: |
          source version.txt
          export BUILDMAJORVERSION="0"
          export BUILDMINORVERSION="5"
          if [[ ! "$BUILDBRANCH" == "*dev" ]]
            then
            # shellcheck disable=2269
            export BUILDPATCHVERSION="${BUILDPATCHVERSION}"
          fi
          export BUILDCOMMITSHA="${BUILDCOMMITSHA}"
          export BUILDSHORTCOMMITSHA="$(echo "${BUILDCOMMITSHA}" | cut -c 1-7)"
          export BUILDDATE="$(date)"
          export BUILDPLATFORM="${BUILDPLATFORM}"
          export PLANCACHEENABLED="true"

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --snapshot --clean --config .github/goreleaser/.goreleaser-for-linux.yaml

  build-macos-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --snapshot --clean --config .github/goreleaser/.goreleaser-for-darwin.yaml

  build-windows-binary:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --snapshot --clean --config .github/goreleaser/.goreleaser-for-windows.yaml