name: build

on:
  push:
    branches:
      - 'dev'
      - 'main'
    tags:
      - 'v*'

env:
  GH_ACCESS_TOKEN: ${{ secrets.FORK_STACKQL_TOKEN }}

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Install cross-compiler for linux/arm64
        run: sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GH_ACCESS_TOKEN }}
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --config .github/goreleaser/.goreleaser-for-linux.yaml
        env:
          GITHUB_TOKEN: ${{env.GH_ACCESS_TOKEN}}

  build-macos-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --config .github/goreleaser/.goreleaser-for-darwin.yaml
        env:
          GITHUB_TOKEN: ${{env.GH_ACCESS_TOKEN}}

  build-windows-binary:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --config .github/goreleaser/.goreleaser-for-windows.yaml
        env:
          GITHUB_TOKEN: ${{env.GH_ACCESS_TOKEN}}