name: build

on:
  push:
    branches:
      - 'dev'

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Install cross-compiler for linux/arm64
        run: sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean --config .github/workflows/.goreleaser-for-linux.yaml

  build-macos-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --snapshot --config .github/workflows/.goreleaser-for-darwin.yaml

  build-windows-binary:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --snapshot --config .github/workflows/.goreleaser-for-windows.yaml